"use client";

import { useEffect, useRef, useState } from "react";
import { Button, Card, CardContent, CardHeader, CardTitle, Input } from "@/components/ui";

type Item = { id:string; title:string|null; mediaType:"IMAGE"|"VIDEO"; originalName:string; fileSize:number; durationSeconds:number; sortOrder:number; active:boolean; previewUrl:string };
const size = (bytes:number) => bytes >= 1048576 ? (bytes/1048576).toFixed(1)+" MB" : Math.ceil(bytes/1024)+" KB";

export function MachineMediaManager({ machineId }: { machineId:string }) {
  const [items,setItems]=useState<Item[]>([]), [open,setOpen]=useState(false), [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [error,setError]=useState("");
  const [title,setTitle]=useState(""), [duration,setDuration]=useState(8); const fileRef=useRef<HTMLInputElement>(null);
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/machines/"+machineId+"/media",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Gagal memuat playlist");setItems(data.media||[]);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Gagal memuat playlist")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[machineId]);
  const upload=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const file=fileRef.current?.files?.[0];if(!file){setError("Pilih foto atau video terlebih dahulu");return}setBusy(true);setError("");const form=new FormData();form.set("file",file);form.set("title",title);form.set("durationSeconds",String(duration));try{const response=await fetch("/api/machines/"+machineId+"/media",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Upload gagal");setItems(current=>[...current,data.media]);setTitle("");if(fileRef.current)fileRef.current.value=""}catch(cause){setError(cause instanceof Error?cause.message:"Upload gagal")}finally{setBusy(false)}};
  const update=async(id:string,patch:Partial<Pick<Item,"active"|"durationSeconds"|"sortOrder"|"title">>)=>{setError("");const response=await fetch("/api/machines/"+machineId+"/media/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const data=await response.json();if(!response.ok){setError(data.error||"Perubahan gagal disimpan");return false}setItems(current=>current.map(item=>item.id===id?data.media:item).sort((a,b)=>a.sortOrder-b.sortOrder));return true};
  const move=async(index:number,direction:-1|1)=>{const other=index+direction;if(other<0||other>=items.length)return;setBusy(true);await Promise.all([update(items[index].id,{sortOrder:items[other].sortOrder}),update(items[other].id,{sortOrder:items[index].sortOrder})]);await load();setBusy(false)};
  const remove=async(item:Item)=>{if(!confirm("Hapus media ini dari playlist mesin?"))return;setBusy(true);const response=await fetch("/api/machines/"+machineId+"/media/"+item.id,{method:"DELETE"});const data=await response.json();if(!response.ok)setError(data.error||"Media gagal dihapus");else setItems(current=>current.filter(value=>value.id!==item.id));setBusy(false)};
  const active=items.filter(item=>item.active).length;
  return <Card><CardHeader className="flex-row items-center justify-between gap-3"><div><CardTitle>Playlist Iklan RVM</CardTitle><p className="mt-1 text-xs text-muted">{active?active+" media aktif · tersinkron otomatis":"Nonaktif · layar QR standar tetap digunakan"}</p></div><Button type="button" variant="outline" size="sm" onClick={()=>setOpen(value=>!value)}>{open?"Tutup":"Kelola"}</Button></CardHeader>
  {open?<CardContent className="space-y-4"><form onSubmit={upload} className="space-y-3 rounded-xl border border-border bg-slate-50 p-3"><input ref={fileRef} type="file" required accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" className="block w-full text-xs text-muted file:mr-3 file:rounded-lg file:border-0 file:bg-brand-100 file:px-3 file:py-2 file:font-semibold file:text-brand-700"/><div className="grid grid-cols-[1fr_90px] gap-2"><Input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Judul brand (opsional)" maxLength={100}/><Input type="number" min={3} max={60} value={duration} onChange={event=>setDuration(Number(event.target.value)||8)} title="Durasi foto (detik)"/></div><div className="flex items-center justify-between gap-3"><p className="text-[11px] text-muted">Foto maks. 12 MB · video maks. 150 MB.</p><Button type="submit" size="sm" disabled={busy}>{busy?"Mengunggah…":"Upload"}</Button></div></form>
  {error?<p className="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700">{error}</p>:null}
  {loading?<p className="py-4 text-center text-sm text-muted">Memuat playlist…</p>:items.length?<div className="space-y-2">{items.map((item,index)=><article key={item.id} className={(item.active?"border-border":"border-dashed border-slate-300 opacity-65")+" grid grid-cols-[76px_1fr] gap-3 rounded-xl border p-2"}><div className="h-16 overflow-hidden rounded-lg bg-slate-900">{item.mediaType==="IMAGE"?<img src={item.previewUrl} alt="" className="h-full w-full object-cover"/>:<video src={item.previewUrl} muted preload="metadata" className="h-full w-full object-cover"/>}</div><div className="min-w-0"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.title||item.originalName}</p><p className="text-[11px] text-muted">{item.mediaType==="IMAGE"?"Foto · "+item.durationSeconds+" detik":"Video · durasi asli"} · {size(item.fileSize)}</p></div><button type="button" disabled={busy} onClick={()=>void update(item.id,{active:!item.active})} className={(item.active?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-600")+" shrink-0 rounded-full px-2 py-1 text-[10px] font-bold"}>{item.active?"AKTIF":"MATI"}</button></div><div className="mt-2 flex items-center gap-1"><button type="button" disabled={busy||index===0} onClick={()=>void move(index,-1)} className="rounded border border-border px-2 py-1 text-xs disabled:opacity-30">↑</button><button type="button" disabled={busy||index===items.length-1} onClick={()=>void move(index,1)} className="rounded border border-border px-2 py-1 text-xs disabled:opacity-30">↓</button>{item.mediaType==="IMAGE"?<input type="number" min={3} max={60} defaultValue={item.durationSeconds} onBlur={event=>void update(item.id,{durationSeconds:Number(event.target.value)})} className="ml-1 w-14 rounded border border-border px-2 py-1 text-xs"/>:null}<button type="button" disabled={busy} onClick={()=>void remove(item)} className="ml-auto rounded px-2 py-1 text-xs font-medium text-red-600">Hapus</button></div></div></article>)}</div>:<div className="rounded-xl border border-dashed border-border p-5 text-center"><p className="text-sm font-medium">Belum ada iklan untuk mesin ini</p><p className="mt-1 text-xs text-muted">RVM akan memakai layar QR standar.</p></div>}</CardContent>:null}</Card>;
}
